version: '3.1'

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: always
    ports:
      - '3306:3306'
    env_file: .env.local
    volumes:
      - ./data:/var/lib/mysql
      - ./schema/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./schema/dummy.sql:/docker-entrypoint-initdb.d/dummy.sql
volumes:
  mariadb:
    driver: local
