USE HomersDB;

CREATE TABLE Hello(
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    content TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE User (
    _id INT AUTO_INCREMENT,
    email VARCHAR(255),
    password VARCHAR(255) NOT NULL,
    fullName VARCHAR(255),
    username VARCHAR(255),
    profileImage VARCHAR(255),
    coverImage VARCHAR(255),
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updateAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (_id)
);

CREATE TABLE Channel (
    _id INT AUTO_INCREMENT,
    description TEXT,
    name VARCHAR(255),
    createAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updateAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (_id)
);

CREATE TABLE Post (
    _id INT AUTO_INCREMENT,
    image VARCHAR(255),
    imagePublicId VARCHAR(255),
    title TEXT,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    userId INT NOT NULL,
    channelId INT NOT NULL,
    PRIMARY KEY (_id),
    FOREIGN KEY (userId) REFERENCES User(_id),
    FOREIGN KEY (channelId) REFERENCES Channel(_id)
);

CREATE TABLE Comment (
    _id INT AUTO_INCREMENT,
    comment TEXT,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    userId INT NOT NULL,
    postId INT NOT NULL,
    PRIMARY KEY (_id),
    FOREIGN KEY (userId) REFERENCES User(_id),
    FOREIGN KEY (postId) REFERENCES Post(_id)
);

CREATE TABLE Follow (
    _id INT AUTO_INCREMENT,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    followerId INT NOT NULL,
    followingId INT NOT NULL,
    PRIMARY KEY (_id),
    FOREIGN KEY (followerId) REFERENCES User(_id),
    FOREIGN KEY (followingId) REFERENCES User(_id)
);

CREATE TABLE Like (
    _id INT KEY AUTO_INCREMENT,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    userId INT NOT NULL,
    postId INT NOT NULL,
    PRIMARY KEY (_id),
    FOREIGN KEY (userId) REFERENCES User(_id),
    FOREIGN KEY (postId) REFERENCES Post(_id)
);
